SELECT DIG.FILE_NBR, 
       CAN.FILE_NBR,
       DIG.STATUS,
       CAN.STATUS, 
       DIG.EFFECTIVE_DATE, 
       CAN.EFFECTIVE_DATE
FROM 
    (SELECT
          DS.FILE_CHR AS FILE_NBR,
          SG.STAGE_NME AS STAGE,
          TT.ACTIVATION_CDE,
          TT.STATUS_NME AS STATUS,
          TO_CHAR(TS.EFFECTIVE_DAT, 'YYYY-MM-DD' ) AS EFFECTIVE_DATE,
          OU.UNIT_NAME     
    FROM WHSE_TANTALIS.TA_DISPOSITION_TRANSACTIONS DT 
      JOIN WHSE_TANTALIS.TA_DISP_TRANS_STATUSES TS
        ON DT.DISPOSITION_TRANSACTION_SID = TS.DISPOSITION_TRANSACTION_SID 
          AND TS.EXPIRY_DAT IS NULL
      JOIN WHSE_TANTALIS.TA_DISPOSITIONS DS
        ON DS.DISPOSITION_SID = DT.DISPOSITION_SID
      JOIN WHSE_TANTALIS.TA_STAGES SG 
        ON SG.CODE_CHR = TS.CODE_CHR_STAGE
      JOIN WHSE_TANTALIS.TA_STATUS TT 
        ON TT.CODE_CHR = TS.CODE_CHR_STATUS
      JOIN WHSE_TANTALIS.TA_ORGANIZATION_UNITS OU 
        ON OU.ORG_UNIT_SID = DT.ORG_UNIT_SID
        WHERE OU.UNIT_NAME = 'VI - LAND MGMNT - VANCOUVER ISLAND SERVICE REGION'
        AND DS.FILE_CHR <> '0000000'
        AND TT.STATUS_NME= 'DISPOSITION IN GOOD STANDING'
        ORDER BY TS.EFFECTIVE_DAT DESC) DIG 

JOIN 

(SELECT
      DS.FILE_CHR AS FILE_NBR,
      SG.STAGE_NME AS STAGE,
      TT.ACTIVATION_CDE,
      TT.STATUS_NME AS STATUS,
          TO_CHAR(TS.EFFECTIVE_DAT, 'YYYY-MM-DD' ) AS EFFECTIVE_DATE,
      OU.UNIT_NAME     
FROM WHSE_TANTALIS.TA_DISPOSITION_TRANSACTIONS DT 
  JOIN WHSE_TANTALIS.TA_DISP_TRANS_STATUSES TS
    ON DT.DISPOSITION_TRANSACTION_SID = TS.DISPOSITION_TRANSACTION_SID 
      AND TS.EXPIRY_DAT IS NULL
  JOIN WHSE_TANTALIS.TA_DISPOSITIONS DS
    ON DS.DISPOSITION_SID = DT.DISPOSITION_SID
  JOIN WHSE_TANTALIS.TA_STAGES SG 
    ON SG.CODE_CHR = TS.CODE_CHR_STAGE
  JOIN WHSE_TANTALIS.TA_STATUS TT 
    ON TT.CODE_CHR = TS.CODE_CHR_STATUS
  JOIN WHSE_TANTALIS.TA_ORGANIZATION_UNITS OU 
    ON OU.ORG_UNIT_SID = DT.ORG_UNIT_SID
    
WHERE  OU.UNIT_NAME = 'VI - LAND MGMNT - VANCOUVER ISLAND SERVICE REGION'
AND SG.STAGE_NME = 'TENURE' 
AND TT.STATUS_NME = 'CANCELLED'
ORDER BY TS.EFFECTIVE_DAT DESC)CAN 

ON DIG.FILE_NBR = CAN.FILE_NBR
AND DIG.EFFECTIVE_DATE = CAN.EFFECTIVE_DATE

ORDER BY DIG.EFFECTIVE_DATE DESC;
