SELECT *
FROM (
  SELECT
    CAST(DT.DISPOSITION_TRANSACTION_SID AS NUMBER) AS DISPOSITION_TRANSACTION_ID,
    DS.FILE_CHR AS FILE_NBR,
    SG.STAGE_NME AS STAGE,
    TT.STATUS_NME AS STATUS,
    DT.APPLICATION_TYPE_CDE AS APPLICATION_TYPE,
    TS.EFFECTIVE_DAT AS EFFECTIVE_DATE,
    ROW_NUMBER() OVER (PARTITION BY DS.FILE_CHR ORDER BY TS.EFFECTIVE_DAT DESC) AS ROW_NUM,
    TY.TYPE_NME AS TENURE_TYPE,
    ST.SUBTYPE_NME AS TENURE_SUBTYPE,
    PU.PURPOSE_NME AS TENURE_PURPOSE,
    SP.SUBPURPOSE_NME AS TENURE_SUBPURPOSE,
    DT.RECEIVED_DAT AS RECEIVED_DATE,
    DT.COMMENCEMENT_DAT AS COMMENCEMENT_DATE,
    DT.EXPIRY_DAT AS EXPIRY_DATE,
    ROUND(IP.AREA_HA_NUM,2) AS AREA_HA,
    DT.LOCATION_DSC,
    SP.SHAPE  

    
  FROM WHSE_TANTALIS.TA_DISPOSITION_TRANSACTIONS DT 
    JOIN WHSE_TANTALIS.TA_INTEREST_PARCELS IP 
      ON DT.DISPOSITION_TRANSACTION_SID = IP.DISPOSITION_TRANSACTION_SID
        AND IP.EXPIRY_DAT IS NULL
    JOIN WHSE_TANTALIS.TA_DISP_TRANS_STATUSES TS
      ON DT.DISPOSITION_TRANSACTION_SID = TS.DISPOSITION_TRANSACTION_SID 
        AND TS.EXPIRY_DAT IS NULL
    JOIN WHSE_TANTALIS.TA_DISPOSITIONS DS
      ON DS.DISPOSITION_SID = DT.DISPOSITION_SID
    JOIN WHSE_TANTALIS.TA_STAGES SG 
      ON SG.CODE_CHR = TS.CODE_CHR_STAGE
    JOIN WHSE_TANTALIS.TA_STATUS TT 
      ON TT.CODE_CHR = TS.CODE_CHR_STATUS
    JOIN WHSE_TANTALIS.TA_AVAILABLE_TYPES TY 
      ON TY.TYPE_SID = DT.TYPE_SID    
    JOIN WHSE_TANTALIS.TA_AVAILABLE_SUBTYPES ST 
      ON ST.SUBTYPE_SID = DT.SUBTYPE_SID 
        AND ST.TYPE_SID = DT.TYPE_SID 
    JOIN WHSE_TANTALIS.TA_AVAILABLE_PURPOSES PU 
      ON PU.PURPOSE_SID = DT.PURPOSE_SID    
    JOIN WHSE_TANTALIS.TA_AVAILABLE_SUBPURPOSES SP 
      ON SP.SUBPURPOSE_SID = DT.SUBPURPOSE_SID 
        AND SP.PURPOSE_SID = DT.PURPOSE_SID 
    JOIN WHSE_TANTALIS.TA_ORGANIZATION_UNITS OU 
      ON OU.ORG_UNIT_SID = DT.ORG_UNIT_SID 
    JOIN WHSE_TANTALIS.TA_TENANTS TE 
      ON TE.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
        AND TE.SEPARATION_DAT IS NULL
        AND TE.PRIMARY_CONTACT_YRN = 'Y'
    JOIN WHSE_TANTALIS.TA_INTERESTED_PARTIES PR
      ON PR.INTERESTED_PARTY_SID = TE.INTERESTED_PARTY_SID
    JOIN WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES SP
      ON SP.INTRID_SID = IP.INTRID_SID
  WHERE DS.FILE_CHR IN ('0343634','1402075','1403046','1403313','1405184','1411184','1413741','1413764',
                        '1413797','1414226','1414247','','2402966','2402970','2403066','2404120','2404443','2407751')
) TN

WHERE TN.ROW_NUM = 1;
