SELECT
      CAST(IP.INTRID_SID AS NUMBER) INTRID_SID,
      CAST(DT.DISPOSITION_TRANSACTION_SID AS NUMBER) DISPOSITION_TRANSACTION_SID,
      DS.FILE_CHR,
      SG.STAGE_NME,
      DS.ACTIVATION_CDE,
      TT.STATUS_NME,
      TS.EFFECTIVE_DAT,
      TY.TYPE_NME,
      ST.SUBTYPE_NME,
      PU.PURPOSE_NME,
      SP.SUBPURPOSE_NME,
      DT.DOCUMENT_CHR,
      DT.RECEIVED_DAT,
      DT.ENTERED_DAT,
      DT.COMMENCEMENT_DAT,
      DT.EXPIRY_DAT AS DT_EXPIRY_DAT,
      IP.AREA_CALC_CDE,
      IP.AREA_HA_NUM,
      DT.LOCATION_DSC,
      OU.UNIT_NAME,
      IP.LEGAL_DSC,
      IH.ORGANIZATIONS_LEGAL_NAME AS HOLDER_ORGANNSATION_NAME,
      IH.INDIVIDUALS_FIRST_NAME || ' ' || IH.INDIVIDUALS_LAST_NAME AS HOLDER_INDIVIDUAL_NAME,
      IH.CITY AS HOLDER_CITY,
      IH.REGION_CDE AS HOLDER_REGION,
      IH.COUNTRY_CDE AS HOLDER_COUNTRY,
      PR.WORK_AREA_CODE || PR.WORK_EXTENSION_NUMBER|| PR.WORK_PHONE_NUMBER AS HOLDER_PHONE,
      SP.SHAPE
FROM WHSE_TANTALIS.TA_DISPOSITION_TRANSACTIONS DT 
  JOIN WHSE_TANTALIS.TA_INTEREST_PARCELS IP 
    ON DT.DISPOSITION_TRANSACTION_SID = IP.DISPOSITION_TRANSACTION_SID
      AND IP.EXPIRY_DAT IS NULL
  JOIN WHSE_TANTALIS.TA_DISP_TRANS_STATUSES TS
    ON DT.DISPOSITION_TRANSACTION_SID = TS.DISPOSITION_TRANSACTION_SID 
      AND TS.EXPIRY_DAT IS NULL
  JOIN WHSE_TANTALIS.TA_DISPOSITIONS DS
    ON DS.DISPOSITION_SID = DT.DISPOSITION_SID
  JOIN WHSE_TANTALIS.TA_STAGES SG 
    ON SG.CODE_CHR = TS.CODE_CHR_STAGE
  JOIN WHSE_TANTALIS.TA_STATUS TT 
    ON TT.CODE_CHR = TS.CODE_CHR_STATUS
  JOIN WHSE_TANTALIS.TA_AVAILABLE_TYPES TY 
    ON TY.TYPE_SID = DT.TYPE_SID    
  JOIN WHSE_TANTALIS.TA_AVAILABLE_SUBTYPES ST 
    ON ST.SUBTYPE_SID = DT.SUBTYPE_SID 
      AND ST.TYPE_SID = DT.TYPE_SID 
  JOIN WHSE_TANTALIS.TA_AVAILABLE_PURPOSES PU 
    ON PU.PURPOSE_SID = DT.PURPOSE_SID    
  JOIN WHSE_TANTALIS.TA_AVAILABLE_SUBPURPOSES SP 
    ON SP.SUBPURPOSE_SID = DT.SUBPURPOSE_SID 
      AND SP.PURPOSE_SID = DT.PURPOSE_SID 
   JOIN WHSE_TANTALIS.TA_ORGANIZATION_UNITS OU 
    ON OU.ORG_UNIT_SID = DT.ORG_UNIT_SID 
   JOIN (SELECT MIN (B.ROW_UNIQUEID), 
               B.DISPOSITION_TRANSACTION_SID,
               B.INTERESTED_PARTY_SID,
               B.ORGANIZATIONS_LEGAL_NAME,
               B.INDIVIDUALS_FIRST_NAME,
               B.INDIVIDUALS_LAST_NAME,
               B.CITY,
               B.COUNTRY_CDE,
               B.REGION_CDE
        FROM WHSE_TANTALIS.TA_INTEREST_HOLDER_VW B

        GROUP BY B.DISPOSITION_TRANSACTION_SID,
               B.INTERESTED_PARTY_SID,
               B.ORGANIZATIONS_LEGAL_NAME,
               B.INDIVIDUALS_FIRST_NAME,
               B.INDIVIDUALS_LAST_NAME,
               B.CITY,
               B.COUNTRY_CDE,
               B.REGION_CDE) IH
    ON IH.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
   JOIN WHSE_TANTALIS.TA_INTERESTED_PARTIES PR
    ON PR.INTERESTED_PARTY_SID = IH.INTERESTED_PARTY_SID
   JOIN WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES SP
    ON SP.INTRID_SID = IP.INTRID_SID;
