SELECT t.*, DISPOSITION_TRANSACTION_SID,INTERESTED_PARTY_SID,
      MIN(ROW_UNIQUEID)

FROM whse_tantalis.TA_INTEREST_HOLDER_VW t 

where DISPOSITION_TRANSACTION_SID = 905814

GROUP BY DISPOSITION_TRANSACTION_SID, INTERESTED_PARTY_SID;




SELECT
      CAST(IP.INTRID_SID AS NUMBER) INTRID_SID,
      CAST(DT.DISPOSITION_TRANSACTION_SID AS NUMBER) DISPOSITION_TRANSACTION_SID,
      DS.FILE_CHR,
      SG.STAGE_NME,
      DS.ACTIVATION_CDE,
      TT.STATUS_NME,
      TS.EFFECTIVE_DAT,
      TY.TYPE_NME,
      ST.SUBTYPE_NME,
      PU.PURPOSE_NME,
      SP.SUBPURPOSE_NME,
      DT.DOCUMENT_CHR,
      DT.RECEIVED_DAT,
      DT.ENTERED_DAT,
      DT.COMMENCEMENT_DAT,
      DT.EXPIRY_DAT AS DT_EXPIRY_DAT,
      IP.AREA_CALC_CDE,
      IP.AREA_HA_NUM,
      DT.LOCATION_DSC,
      --OU.UNIT_NAME,
      --IP.LEGAL_DSC,
      IH.ORGANIZATIONS_LEGAL_NAME AS HOLDER_ORGANNSATION_NAME,
      IH.INDIVIDUALS_FIRST_NAME || ' ' || IH.INDIVIDUALS_LAST_NAME AS HOLDER_INDIVIDUAL_NAME,
      IH.CITY AS HOLDER_CITY,
      IH.REGION_CDE AS HOLDER_REGION,
      IH.COUNTRY_CDE AS HOLDER_COUNTRY,
      PR.WORK_AREA_CODE || PR.WORK_EXTENSION_NUMBER|| PR.WORK_PHONE_NUMBER AS HOLDER_PHONE

FROM whse_tantalis.ta_disposition_transactions dt 
  JOIN whse_tantalis.ta_interest_parcels ip 
    ON dt.DISPOSITION_TRANSACTION_SID = ip.DISPOSITION_TRANSACTION_SID
      AND IP.EXPIRY_DAT is NULL
  JOIN whse_tantalis.ta_disp_trans_statuses ts
    ON dt.DISPOSITION_TRANSACTION_SID = ts.DISPOSITION_TRANSACTION_SID 
      AND ts.EXPIRY_DAT is NULL
  JOIN whse_tantalis.ta_dispositions ds
    ON ds.DISPOSITION_SID = dt.DISPOSITION_SID
  JOIN whse_tantalis.ta_stages sg 
    ON sg.CODE_CHR = ts.CODE_CHR_STAGE
  JOIN whse_tantalis.ta_status tt 
    ON tt.CODE_CHR = ts.CODE_CHR_STATUS
  JOIN whse_tantalis.ta_available_types ty 
    ON ty.TYPE_SID = dt.TYPE_SID    
  JOIN whse_tantalis.ta_available_subtypes st 
    ON st.SUBTYPE_SID = dt.SUBTYPE_SID 
      AND st.TYPE_SID = dt.TYPE_SID 
  JOIN whse_tantalis.ta_available_purposes pu 
    ON pu.PURPOSE_SID = dt.PURPOSE_SID    
  JOIN whse_tantalis.ta_available_subpurposes sp 
    ON sp.SUBPURPOSE_SID = dt.SUBPURPOSE_SID 
      AND sp.PURPOSE_SID = dt.PURPOSE_SID 
   JOIN whse_tantalis.ta_organization_units ou 
    ON ou.ORG_UNIT_SID = dt.ORG_UNIT_SID 
    
    
    
   JOIN WHSE_TANTALIS.TA_INTEREST_HOLDER_VW IH
    ON IH.DISPOSITION_TRANSACTION_SID = DT.DISPOSITION_TRANSACTION_SID
      GROUP BY  IH.DISPOSITION_TRANSACTION_SID, IH.INTERESTED_PARTY_SID
    
    
    
   JOIN WHSE_TANTALIS.TA_INTERESTED_PARTIES PR
    ON PR.INTERESTED_PARTY_SID = IH.INTERESTED_PARTY_SID
    
