SELECT
        CAST(MM.INTRID_SID AS NUMBER) INTRID_SID,
        CAST(MM.DISPOSITION_TRANSACTION_SID AS NUMBER) DISPOSITION_TRANSACTION_SID,
        NN.FILE_CHR,
        NN.STAGE_NME,
        NN.DTS_ACTIVATION_CDE,
        NN.STATUS_NME,
        NN.APPLICATION_TYPE_CDE,
        NN.PURPOSE_NME,
        NN.SUBPURPOSE_NME,
        NN.TYPE_NME,
        NN.SUBTYPE_NME,
        NN.DOCUMENT_CHR,
        NN.RECEIVED_DAT,
        NN.ENTERED_DAT,
        NN.EFFECTIVE_DAT,
        NN.COMMENCEMENT_DAT,
        MM.EXPIRY_DAT AS P_EXPIRY_DAT,
        NN.DT_EXPIRY_DAT,
        MM.AREA_CALC_CDE,
        MM.AREA_HA_NUM,
        NN.LOCATION_DSC,
        MM.LEGAL_DSC,
        NN.ORGANIZATIONS_LEGAL_NAME AS HOLDER_ORGANNSATION_NAME,
        NN.INDIVIDUALS_FIRST_NAME || ' ' || NN.INDIVIDUALS_LAST_NAME AS HOLDER_INDIVIDUAL_NAME,
        NN.CITY AS HOLDER_CITY,
        NN.REGION_CDE AS HOLDER_REGION,
        NN.COUNTRY_CDE AS HOLDER_COUNTRY,
        NN.WORK_AREA_CODE || NN.WORK_EXTENSION_NUMBER|| NN.WORK_PHONE_NUMBER AS HOLDER_PHONE
        --XX.SHAPE
  FROM (SELECT
       CAST(JJ.DISPOSITION_TRANSACTION_SID AS NUMBER) DISPOSITION_TRANSACTION_SID,
       CAST(JJ.DISPOSITION_SID AS NUMBER) DISPOSITION_SID,
       KK.ACTIVATION_CDE AS D_ACTIVATION_CDE,
       KK.FILE_CHR,
       JJ.PURPOSE_NME,
       JJ.SUBPURPOSE_NME,
       JJ.TYPE_NME,
       JJ.SUBTYPE_NME,
       JJ.UNIT_NAME,
       JJ.STREET_ADDRESS,
       JJ.PROVINCE_ABBR,
       JJ.APPLICATION_TYPE_CDE,
       JJ.COMMENCEMENT_DAT,
       JJ.DOCUMENT_CHR,
       JJ.ENTERED_DAT,
       JJ.EXPIRY_DAT AS DT_EXPIRY_DAT,
       JJ.LOCATION_DSC,
       JJ.OFFER_TIMBER_DEFERMENT_YRN,
       JJ.RECEIVED_DAT,
       JJ.SURFACE_OR_UNDER_CDE,
       JJ.TIMBER_VALUE_DLR,
       LL.EFFECTIVE_DAT,
       LL.CODE_CHR_STATUS,
       LL.STATUS_NME,
       LL.DTS_ACTIVATION_CDE,
       LL.STATUS_EXPIRY_DAT,
       LL.CODE_CHR_STAGE,
       LL.STAGE_NME,
       LL.STAGE_EXPIRY_DAT,
       JJ.ORGANIZATIONS_LEGAL_NAME,
       JJ.INDIVIDUALS_FIRST_NAME,
       JJ.INDIVIDUALS_LAST_NAME,
       JJ.CITY,
       JJ.REGION_CDE,
       JJ.COUNTRY_CDE,
       JJ.WORK_AREA_CODE,
       JJ.WORK_EXTENSION_NUMBER,
       JJ.WORK_PHONE_NUMBER
       
 FROM (SELECT
       CAST(AA.DISPOSITION_TRANSACTION_SID AS NUMBER) DISPOSITION_TRANSACTION_SID,
       CAST(AA.DISPOSITION_SID AS NUMBER) DISPOSITION_SID,
       BB.PURPOSE_NME,
       CC.SUBPURPOSE_NME,
       DD.TYPE_NME,
       EE.SUBTYPE_NME,
       FF.UNIT_NAME,
       FF.STREET_ADDRESS,
       FF.PROVINCE_ABBR,
       FF.COUNTRY,
       FF.POSTAL_CODE,
       AA.APPLICATION_TYPE_CDE,
       AA.COMMENCEMENT_DAT,
       AA.DOCUMENT_CHR,
       AA.ENTERED_DAT,
       AA.EXPIRY_DAT,
       AA.LOCATION_DSC,
       AA.OFFER_TIMBER_DEFERMENT_YRN,
       AA.RECEIVED_DAT,
       AA.SURFACE_OR_UNDER_CDE,
       AA.TIMBER_VALUE_DLR,
       SS.ORGANIZATIONS_LEGAL_NAME,
       SS.INDIVIDUALS_FIRST_NAME,
       SS.INDIVIDUALS_LAST_NAME,
       SS.CITY,
       SS.REGION_CDE,
       SS.COUNTRY_CDE,
       ZZ.WORK_AREA_CODE,
       ZZ.WORK_EXTENSION_NUMBER,
       ZZ.WORK_PHONE_NUMBER
 FROM
       WHSE_TANTALIS.TA_DISPOSITION_TRANSACTIONS AA,
       WHSE_TANTALIS.TA_AVAILABLE_PURPOSES BB,
       WHSE_TANTALIS.TA_AVAILABLE_SUBPURPOSES CC,
       WHSE_TANTALIS.TA_AVAILABLE_TYPES DD,
       WHSE_TANTALIS.TA_AVAILABLE_SUBTYPES EE,
       WHSE_TANTALIS.TA_ORGANIZATION_UNITS FF,                             
       WHSE_TANTALIS.TA_INTEREST_HOLDER_VW SS,
       WHSE_TANTALIS.TA_INTERESTED_PARTIES ZZ
 WHERE
       SS.DISPOSITION_TRANSACTION_SID = AA.DISPOSITION_TRANSACTION_SID(+) AND
       ZZ.INTERESTED_PARTY_SID = SS.INTERESTED_PARTY_SID(+) AND
       AA.PURPOSE_SID = BB.PURPOSE_SID AND
       BB.PURPOSE_SID = CC.PURPOSE_SID AND
       AA.SUBPURPOSE_SID = CC.SUBPURPOSE_SID AND
       AA.TYPE_SID = DD.TYPE_SID AND
       DD.TYPE_SID = EE.TYPE_SID AND
       AA.SUBTYPE_SID = EE.SUBTYPE_SID AND
       AA.ORG_UNIT_SID = FF.ORG_UNIT_SID 
 ORDER BY
       AA.DISPOSITION_TRANSACTION_SID) JJ,
       WHSE_TANTALIS.TA_DISPOSITIONS KK,
       (SELECT GG.DISPOSITION_TRANSACTION_SID,
       GG.EFFECTIVE_DAT,
       GG.CODE_CHR_STATUS,
       HH.STATUS_NME,
       HH.ACTIVATION_CDE AS DTS_ACTIVATION_CDE,
       HH.EXPIRY_DAT AS STATUS_EXPIRY_DAT,
       GG.CODE_CHR_STAGE,
       II.STAGE_NME,
       GG.EXPIRY_DAT AS STAGE_EXPIRY_DAT
FROM
       WHSE_TANTALIS.TA_DISP_TRANS_STATUSES GG,
       WHSE_TANTALIS.TA_STATUS HH,
       WHSE_TANTALIS.TA_STAGES II
WHERE
       GG.CODE_CHR_STATUS = HH.CODE_CHR AND
       GG.CODE_CHR_STAGE = II.CODE_CHR AND
       GG.EXPIRY_DAT IS NULL
ORDER BY
       GG.DISPOSITION_TRANSACTION_SID) LL
  WHERE
       JJ.DISPOSITION_SID = KK.DISPOSITION_SID(+) AND
       JJ.DISPOSITION_TRANSACTION_SID = LL.DISPOSITION_TRANSACTION_SID(+)
  ORDER BY
       JJ.DISPOSITION_TRANSACTION_SID) NN,

      WHSE_TANTALIS.TA_INTEREST_PARCELS MM,
      WHSE_TANTALIS.TA_INTEREST_PARCEL_SHAPES XX
WHERE
      MM.DISPOSITION_TRANSACTION_SID(+) = NN.DISPOSITION_TRANSACTION_SID AND
      XX.INTRID_SID = MM.INTRID_SID;
